### PR TITLE
[25] Design improvements

### PR DESCRIPTION
**Pull request by kz8519**
8/11 More edits:

[Updated profile view](https://pxl.cl/29LGm)
- Added section header in profile view to display the label "My invites"
- Deleted the dark blue bar that was previously there
- Rounded the corners of the light blue rectangle displaying profile information

[Other](https://pxl.cl/29LJK)
- Added name of app to initial view
- Added app icon to display from phone's home page
- Added icon to launch screen
- Increased sizes of text fields

8/9 Edits:
- Finished adding auto-layout for the rest of the screens
- Fixed the table view in the profile view so that the cells display as they do in the inbox view and without the extra shadowing (screenshots below)

Before
Simulator Screen Shot - iPhone 11 - 2022-08-09 at 12 07 44

Now

Simulator Screen Shot - iPhone 11 - 2022-08-09 at 12 08 39

### CODE REVIEW

**Review by subbareddyla — CHANGES_REQUESTED** [review]
Please use bigger font for "My invites"

**Comment by subbareddyla** [comment]
One more thing is in the profile cell in https://www.internalfb.com/intern/px/p/29LGm/ increase left margin of profile image as left margin is much less than right margin for profile cell(Hermione Granger).

**Comment by kz8519** [comment]
> One more thing is in the profile cell in https://www.internalfb.com/intern/px/p/29LGm/ increase left margin of profile image as left margin is much less than right margin for profile cell(Hermione Granger).

I've increased the left margin, but I also think part of it is because the name doesn't fill up the entire label, the spacing seems uneven even though the left margin of the photo and the right margin of the labels were originally set to be equal. I'm not yet too sure how to do this, but should I try looking into dynamically spacing the left margin to match with the smallest right margin?

**Comment by kz8519** [comment]
[Newest update for profile view](https://pxl.cl/29M2r)

- increased font size
- increased left margin for profile photo

**Review by subbareddyla — APPROVED** [review]
Looks good.

**Comment by subbareddyla** [comment]
> > One more thing is in the profile cell in https://www.internalfb.com/intern/px/p/29LGm/ increase left margin of profile image as left margin is much less than right margin for profile cell(Hermione Granger).
> 
> I've increased the left margin, but I also think part of it is because the name doesn't fill up the entire label, the spacing seems uneven even though the left margin of the photo and the right margin of the labels were originally set to be equal. I'm not yet too sure how to do this, but should I try looking into dynamically spacing the left margin to match with the smallest right margin?

Apart from left margin smaller than right margin, left margin for profile cell is much smaller than left margin of invites cells which made it look weird. So suggested to update left margin.

**Pull request merged**
